### ISSUE TITLE
Container fails to run on kubernetes (You must install .NET to run this application)

### ISSUE THREAD

**Issue by Scarjit** [Azure-Samples/iot-edge-opc-plc#319]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1) Setup a RHEL 9 VM with kubernetes
2) Install the pod
```
apiVersion: v1
kind: Pod
metadata:
  name: opc-plc-pod
  namespace: united-manufacturing-hub
  labels:
    app: opc-plc
spec:
  containers:
  - name: opc-plc
    image: mcr.microsoft.com/iotedge/opc-plc:latest
    args:
      - "--fn=10000"    #10k tags
      - "--fr=1"
      - "--ft=uint"
      - "--pn=50000"
      - "--autoaccept"
      - "--certdnsnames=united-manufacturing-hub-opc-plc-service,opc-plc-pod"
      - "--plchostname=united-manufacturing-hub-opc-plc-service"
      - "--showpnjsonph"
      - "--unsecuretransport"
      - "--maxsubscriptioncount=10000"
      - "--loglevel=verbose"
    ports:
    - containerPort: 50000
```

### Any log messages given by the failure
![image](https://github.com/Azure-Samples/iot-edge-opc-plc/assets/6317420/de3475a0-a756-4297-8297-1c5f29735597)

### Expected/desired behavior
It shall run (as the same version run on other host operating systems we tested)

### OS and Version?
RHEL 9

### Versions
mcr.microsoft.com/iotedge/opc-plc:latest (`mcr.microsoft.com/iotedge/opc-plc@sha256:a4a32760b69c30e7ab9e30bf4ee3f13e81210ced87c5a5cc3ad8a83f78a7c771`)

### Mention any other details that might be useful
In our testing the same setup ran fine on our flatcar based machines.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
